// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjJKJH3KzNO-D-4dFDS26bokCMN7RkjF8',
    appId: '1:788529643704:web:1be820c83273c1a085f44d',
    messagingSenderId: '788529643704',
    projectId: 'arieldev-docs',
    authDomain: 'arieldev-docs.firebaseapp.com',
    storageBucket: 'arieldev-docs.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp4O4kpZ4gXbvMlQNASFm9cMldGiR_ueg',
    appId: '1:788529643704:android:90f9cf5bfae9516685f44d',
    messagingSenderId: '788529643704',
    projectId: 'arieldev-docs',
    storageBucket: 'arieldev-docs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnp4Io9hke5w5OqEX5IJbri2Gsox02Yq4',
    appId: '1:788529643704:ios:9c78c651e9e9813e85f44d',
    messagingSenderId: '788529643704',
    projectId: 'arieldev-docs',
    storageBucket: 'arieldev-docs.firebasestorage.app',
    iosBundleId: 'com.groovelab.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnp4Io9hke5w5OqEX5IJbri2Gsox02Yq4',
    appId: '1:788529643704:ios:9c78c651e9e9813e85f44d',
    messagingSenderId: '788529643704',
    projectId: 'arieldev-docs',
    storageBucket: 'arieldev-docs.firebasestorage.app',
    iosBundleId: 'com.groovelab.app',
  );
}
